### ISSUE TITLE
Installation failure -- could it be a dependency issue?

### ISSUE THREAD

**Issue by discolemur** [BioHPC/LONGO#2]
Hello,
I'd like to use LONGO for analysis in my lab, but I'm having trouble installing the current build according to your instructions in the README. After installing all of the dependencies, LONGO failed to install. We suspect that the newest versions of the dependencies may be causing the failure. Noting that this repository hasn't been updated for several months, have you tested the current tar.gz archive lately to make sure it can still be installed in R?

I am including an extract of the installation failure message below:
`*** installing help indices
  converting help for package ‘LONGO’
    finding HTML links ... done
    GOanalysis                              html  
    LONGO                                   html  
    LONGOcmd                                html  
    LONGOquotient                           html  
    analyze                                 html  
    callbiomaRt                             html  
    dict                                    html  
    exampleHumanData                        html  
    exampleRatData                          html  
    openfile                                html  
    plotLONGO                               html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
sh: line 1: 143582 Segmentation fault      (core dumped) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/Rtmpi81EuD/file230db2c6997fc'

 *** caught segfault ***
address (nil), cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...`

Thank you for the help!

**Comment by apaul7** [comment]
Hello!
I updated all my packages and dependencies and was still able to install LONGO from that tar file. Can you let me know what `sessionInfo()` outputs?

**Comment by discolemur** [comment]
After more tests, I successfully installed it on a different computer. The first computer is still unable to install LONGO, and this is its `sessionInfo()` output:

R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.28.0

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3 


However, since I have it running on a different computer now, I should be able to continue the analysis without fixing the installation problem on the first computer. Thanks!
